=== jonmikeli/programmez/iot-azure-paas/schemas/reButton/reButtonDataSchema.json
{
    "$schema": "http://json-schema.org/draft-07/schema",
    "type": "object",
    "title": "ReButton IoT message JSON Schema (retroengineering)",
    "description": "",
    "default": {},
    "additionalProperties": true,
    "required": [
        "EnqueuedTimeUtc",
        "Properties",
        "SystemProperties",
        "Body"
    ],
    "properties": {
        "EnqueuedTimeUtc": {
            "$id": "#/properties/EnqueuedTimeUtc",
            "type": "string",
            "default": "",
            "examples": [
                "2020-05-02T21:01:08.1080000Z"
            ]
        },
        "Properties": {
            "$id": "#/properties/Properties",
            "type": "object",
            "default": {},
            "examples": [
                {
                    "productId": "ReButton"
                }
            ],
            "additionalProperties": true,
            "required": [
                "productId"
            ],
            "properties": {
                "productId": {
                    "$id": "#/properties/Properties/properties/productId",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "ReButton"
                    ]
                }
            }
        },
        "SystemProperties": {
            "$id": "#/properties/SystemProperties",
            "type": "object",
            "default": {},
            "examples": [
                {
                    "connectionDeviceId": "buttonDevOpsBuzzer1",
                    "contentType": "application/json",
                    "connectionDeviceGenerationId": "637174884786996293",
                    "contentEncoding": "utf-8",
                    "enqueuedTime": "2020-05-02T21:01:08.1080000Z",
                    "connectionAuthMethod": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}"
                }
            ],
            "additionalProperties": true,
            "required": [
                "connectionDeviceId",
                "connectionAuthMethod",
                "connectionDeviceGenerationId",
                "contentType",
                "contentEncoding",
                "enqueuedTime"
            ],
            "properties": {
                "connectionDeviceId": {
                    "$id": "#/properties/SystemProperties/properties/connectionDeviceId",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "buttonDevOpsBuzzer1"
                    ]
                },
                "connectionAuthMethod": {
                    "$id": "#/properties/SystemProperties/properties/connectionAuthMethod",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}"
                    ]
                },
                "connectionDeviceGenerationId": {
                    "$id": "#/properties/SystemProperties/properties/connectionDeviceGenerationId",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "637174884786996293"
                    ]
                },
                "contentType": {
                    "$id": "#/properties/SystemProperties/properties/contentType",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "application/json"
                    ]
                },
                "contentEncoding": {
                    "$id": "#/properties/SystemProperties/properties/contentEncoding",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "utf-8"
                    ]
                },
                "enqueuedTime": {
                    "$id": "#/properties/SystemProperties/properties/enqueuedTime",
                    "type": "string",
                    "default": "",
                    "examples": [
                        "2020-05-02T21:01:08.1080000Z"
                    ]
                }
            }
        },
        "Body": { 
            "$ref": "#/reButtonBodySchema.json"
        }
    }
}

=== jonmikeli/programmez/iot-azure-paas/data/reButton/reButtonData1.json
{
    "EnqueuedTimeUtc": "2020-05-02T21:01:08.1080000Z",
    "Properties": {
        "productId": "ReButton"
    },
    "SystemProperties": {
        "connectionDeviceId": "buttonDevOpsBuzzer1",
        "connectionAuthMethod": "{\"scope\":\"device\",\"type\":\"sas\",\"issuer\":\"iothub\",\"acceptingIpFilterRule\":null}",
        "connectionDeviceGenerationId": "637174884786996293",
        "contentType": "application/json",
        "contentEncoding": "utf-8",
        "enqueuedTime": "2020-05-02T21:01:08.1080000Z"
    },
    "Body": {
        "actionNum": "1",
        "message": "Single click",
        "singleClick": "Single click",
        "actionCount": 42
    }
}
